### PR TITLE
Fix: emphasize tentative nature of meetings

### PR DESCRIPTION
**Pull request by woutermont**
Action following multiple cases of uncertainty (cf. [matrix](https://matrix.to/#/!rUzJAFxzsTfTWEIQfp:gitter.im/$xEtmuBLbL7tVWIDI8gKVM1wh3u-LLlJIzLsJPOB674g?via=gitter.im&via=matrix.org&via=t2bot.io))

### CODE REVIEW

**Comment by woutermont** [comment]
If this panel also concludes that it will have no more meetings until the decision of the special topic meeting of 2023-10-10,  it might be better to use a text similar to https://github.com/solid/data-interoperability-panel/pull/318/commits/fa0b1b124050c2e20803d9a757315ea4a29dab39.

**Comment by CxRes** [comment]
The tentative has been only this summer. Until that, we met every Thursday for 3 years. What we need to do is revise/renew the  panel charter once eveyone is back.

**Comment by woutermont** [comment]
@CxRes, I had come to believe that this panel would follow the direction of the CG towards a structure based on two central meetings, possibly complemented with breakout task forces. Not sure why or where I got that impression; possibly because @csarven seemed to be in favor of it, and he is chair/editor of this panel/spec.

In any case, do you feel there will be meetings between now and 2023-10-10? If not, I would still merge this PR to shed clarity until then.

**Comment by CxRes** [comment]
This is why I had been so insistent on dealing with the Solid process in entirety rather than just the charter. But there were other compulsions, as I know now.

The reorganization imho is not official until someone pens it down (though I share your impression too). I would continue to presume that we will stick with the current schedule once this self-imposed hiatus is over. If there is a change to the text here, I would rather say we are on a summer/fall hiatus than say tentative slot (which does not accurately reflect history and current process, we are not even discussing tentative slots for this panel)! 

I would request you to hold on till we get a clear picture from @csarven and @elf-pavlik as to their availability and/or some instruction to re-organize from the CG!

**Comment by woutermont** [comment]
> This is why I had been so insistent on dealing with the Solid process in entirety rather than just the charter. 

I don't see what this has to do with the charter. Whether we did this before, during, or after the chartering, fact remains that people are confused, and so it is important to shed some clarity.

> The reorganization imho is not official until someone pens it down (though I share your impression too).

Which whill (hopefully) happen on October 10th. 

> I would continue to presume that we will stick with the current schedule once this self-imposed hiatus is over.

When would that be? 

> If there is a change to the text here, I would rather say we are on a summer/fall hiatus than say tentative slot

Fine for me. I worded it as 'tentative' because that is how this panel has been meeting these summer months: on and off, mostly by ad-hoc conversation on Matrix. But if you want to reword it, please do a suggestion to the PR.

> I would request you to hold on till we get a clear picture from @csarven and @elf-pavlik as to their availability and/or some instruction to re-organize from the CG!

The instructions for reorganization are pretty clear: a special topic meeting has been planned on 2023-10-10 to deal with that. As to this specific PR: this is more urgent, to address the confusion multiple people have brought to the attention. Note that it is just my suggestion to describe the factual status of this panel's meetings, not to change it.

**Comment by CxRes** [comment]
> fact remains that people are confused

I am confused too! :) 

> When would that be?

It depends on Sarven and Pavlik's plans and energy (and really I want to hear from them in their capacity as co-authors). I am happy with a meeting next week even (TPAC this week). Once they chime in, I am ok with text change to "on hiatus"!

And if others are interested in having a meeting and brought this up to you (or have specific concerns), please share it, we can plan something in the interim!

**Review by elf-pavlik — APPROVED** [review]

**Comment by elf-pavlik** [comment]
I think we can bring up https://github.com/solid/process/issues/324 next Wednesday and probe other participants' preferences. In the second week of October we also should already know if WG was approved, please remember that the intention is for the WG to pick up the notifications work as well.

**Comment by csarven** [comment]
Background: https://github.com/solid/specification/pull/458#issue-1390870735 -- so it was intended to transition from panels to task forces.

I suggest convening in solid/specification (so that we can slowly phase out solid/notifications-panel) for notifications discussions and panning adhoc meetings on work items. Major discussions should happen in special topic meetings. Major decisions can be in CG weekly.

**Pull request merged**
