### PR TITLE
Created Webhooks Proposal

### PR DESCRIPTION
**Pull request by jaxoncreed**
A preliminary outline of how WebHooks would work within the notification spec.

I showed up to the meeting on September 30th (Sorry I couldn't come to the meeting last week, I was on vacation). Kevin told me the best first step is to write a more detailed proposal on how WebHooks would work.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Hi @jaxoncreed, how does this conceptually differ from Linked Data Notifications?

**Comment by elf-pavlik** [comment]
> Webhooks are an alternative to websockets that are more useful for server-based use cases. While a websocket solution would require a server to maintain a constant websocket connection with a Pod as long as it wants notifications, webhooks only require one registration.

We need WebHooks style subscription type for work we do in interop. While I see no problem with prioritizing WebSockets, personally I should be able to start implementing (or contributing to the implementation of) WebHook subscription in Typescript starting January 2022.

**Comment by jaxoncreed** [comment]
The main _problem_ is around scalability, as you and elf pointed out. The notifications standard seems to have been designed to have websockets eventually integrated so I wouldn't say that the creation of this spec doesn't indicate that something is broken about the notifications spec, it only details what the spec already implies.

**Comment by acoburn** [comment]
> Wait. I had the 21st as the day of the next meeting. is it not then? What was discussed in this meeting?

[2nd and 4th Thursdays of the month](https://github.com/solid/notifications-panel#participation). We delayed discussing the proposal until Thursday, Oct 28.

**Comment by jaxoncreed** [comment]
Okay, I've made some corrections, and I won't let approval on this be a blocker to start development.

**Comment by TallTed** [comment]
@jaxoncreed @elf-pavlik 

Looking at [the Webhooks Notifications Flow SVG](https://raw.githubusercontent.com/solid/notifications-panel/885dd48bac22bbc4e5bf50f8e3489960c0d38df2/proposals/solid-webhook-notifications-flow.svg), I see a number of curious things.

Why are APIs sometimes treated identically to Servers (which one might expect to serve API calls)? Why is the "Unsubscribe Endpoint" not an "Unsubscribe" call to the "Subscription API", with neither of these on a "Subscription Server"?

How does the "Topic Resource" (which seems most likely to be a document, not an app) know to (and how does it) direct a "Webhook Request" to the (still labeled as) "Client Server"?

Actors (Servers, Clients, Producers, Consumers, etc.) are Agents, and should be distinct from Resources (the Things Agents Act Upon, by Creating, Reading, Updating, Deleting, Transferring [which is a complex Update], etc.). Agents may interact directly with other Agents, or act on/through a mediating Resource.

I think the diagram should make clear what are Agents, and what are Resources, and what Actions the Agents take upon the Resources, and what interactions/communications go direct from Agent to Agent.

**Comment by jaxoncreed** [comment]
> Why are APIs sometimes treated identically to Servers (which one might expect to serve API calls)? Why is the "Unsubscribe Endpoint" not an "Unsubscribe" call to the "Subscription API", with neither of these on a "Subscription Server"?

I agree it's weird. I was following the example set in the original document https://github.com/solid/notifications-panel/blob/main/proposals/solid-notifications.md.

**Comment by csarven** [comment]
In the future, it'd be great if we can refrain from merging own proposals as a CG/panel work item.

@jaxoncreed I'm aware that we ran out of time in the last meeting before getting to concrete resolutions/actions, but have you incorporated the feedback in https://github.com/solid/notifications-panel/blob/main/meetings/2021-10-28.md#webhooks-proposal before merging or created issues to follow-up with?

**Comment by jaxoncreed** [comment]
Oh sorry, I thought the implication for this being open so long despite everyone saying that it should be merged in was that it was my responsibility to merge it.

I'll make a PR for the requested changes.

**Pull request merged**
